env:
  browser: true
  es2021: true
  node: true
  vue/setup-compiler-macros: true
extends:
  - "eslint:recommended"
  - "plugin:import/recommended"
  - "plugin:import/typescript"
  - "plugin:ssr-friendly/recommended"
  - "plugin:vue/vue3-recommended"
  - "@vue/typescript/recommended"
overrides:
  - files: [ "*.config.js" ]
    env:
      node: true
parserOptions:
  ecmaVersion: latest
plugins:
  - "@typescript-eslint"
  - "import"
  - "ssr-friendly"
  - "vue"
settings:
  import/parsers:
    "@typescript-eslint/parser": [ .ts, .tsx ]
  import/resolver:
    - vite
    - typescript:
        alwaysTryTypes: true
rules:
  sort-imports:
    - error
  vue/max-attributes-per-line:
    - off
  vue/multi-word-component-names:
    - error
    - ignores:
      - index.page
  vue/no-v-html:
    - off
  vue/html-closing-bracket-spacing:
    - error
    - startTag: never
      endTag: never
      selfClosingTag: never
